# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'AccuntingApp.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLayout, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTableWidget, QTableWidgetItem, QVBoxLayout, QWidget)
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(712, 606)
        MainWindow.setMinimumSize(QSize(712, 606))
        MainWindow.setMaximumSize(QSize(712, 606))
        MainWindow.setLayoutDirection(Qt.RightToLeft)
        MainWindow.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(230, 250, 250, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
" background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop:0 rgba(245, 240, 235, 255), stop:1 rgba(255, 255, 255, 255));")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(550, 50, 229, 391))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.btn_dashboard = QPushButton(self.verticalLayoutWidget)
        self.btn_dashboard.setObjectName(u"btn_dashboard")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dashboard.sizePolicy().hasHeightForWidth())
        self.btn_dashboard.setSizePolicy(sizePolicy)
        self.btn_dashboard.setStyleSheet(u"border-radius: 50px;")

        self.verticalLayout.addWidget(self.btn_dashboard)

        self.btn_person = QPushButton(self.verticalLayoutWidget)
        self.btn_person.setObjectName(u"btn_person")
        sizePolicy.setHeightForWidth(self.btn_person.sizePolicy().hasHeightForWidth())
        self.btn_person.setSizePolicy(sizePolicy)
        self.btn_person.setLayoutDirection(Qt.RightToLeft)
        self.btn_person.setStyleSheet(u"border-radius: 50px;\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")

        self.verticalLayout.addWidget(self.btn_person)

        self.btn_data = QPushButton(self.verticalLayoutWidget)
        self.btn_data.setObjectName(u"btn_data")
        sizePolicy.setHeightForWidth(self.btn_data.sizePolicy().hasHeightForWidth())
        self.btn_data.setSizePolicy(sizePolicy)
        self.btn_data.setStyleSheet(u"border-radius: 50px;")

        self.verticalLayout.addWidget(self.btn_data)

        self.btn_tafazol = QPushButton(self.verticalLayoutWidget)
        self.btn_tafazol.setObjectName(u"btn_tafazol")
        self.btn_tafazol.setEnabled(True)
        sizePolicy.setHeightForWidth(self.btn_tafazol.sizePolicy().hasHeightForWidth())
        self.btn_tafazol.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamilies([u"N02Jeyran"])
        self.btn_tafazol.setFont(font)
        self.btn_tafazol.setStyleSheet(u"border-radius: 50px;")
        self.btn_tafazol.setFlat(False)

        self.verticalLayout.addWidget(self.btn_tafazol)

        self.btn_manage = QPushButton(self.verticalLayoutWidget)
        self.btn_manage.setObjectName(u"btn_manage")
        sizePolicy.setHeightForWidth(self.btn_manage.sizePolicy().hasHeightForWidth())
        self.btn_manage.setSizePolicy(sizePolicy)
        self.btn_manage.setStyleSheet(u"border-radius: 50px;")

        self.verticalLayout.addWidget(self.btn_manage)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.pushButton_8 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setFamilies([u"B Nazanin"])
        self.pushButton_8.setFont(font1)

        self.horizontalLayout_2.addWidget(self.pushButton_8)

        self.pushButton_5 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy2)
        self.pushButton_5.setFont(font1)

        self.horizontalLayout_2.addWidget(self.pushButton_5)

        self.btn_call = QPushButton(self.verticalLayoutWidget)
        self.btn_call.setObjectName(u"btn_call")
        sizePolicy2.setHeightForWidth(self.btn_call.sizePolicy().hasHeightForWidth())
        self.btn_call.setSizePolicy(sizePolicy2)
        self.btn_call.setFont(font1)

        self.horizontalLayout_2.addWidget(self.btn_call)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(-2, 0, 711, 51))
        self.groupBox.setMinimumSize(QSize(711, 51))
        self.groupBox.setMaximumSize(QSize(711, 51))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(740, 0, 61, 49))
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy3)
        self.label.setMinimumSize(QSize(50, 0))
        font2 = QFont()
        font2.setFamilies([u"B Titr"])
        font2.setPointSize(17)
        self.label.setFont(font2)
        self.lbl_calender_2 = QLabel(self.groupBox)
        self.lbl_calender_2.setObjectName(u"lbl_calender_2")
        self.lbl_calender_2.setGeometry(QRect(550, 16, 71, 20))
        font3 = QFont()
        font3.setPointSize(9)
        self.lbl_calender_2.setFont(font3)
        self.lbl_calender_2.setStyleSheet(u"")
        self.lbl_0 = QLabel(self.groupBox)
        self.lbl_0.setObjectName(u"lbl_0")
        self.lbl_0.setGeometry(QRect(520, 15, 21, 21))
        font4 = QFont()
        font4.setPointSize(7)
        self.lbl_0.setFont(font4)
        self.lbl_0.setStyleSheet(u"image: url(:/icons/calendar.png);")
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 20, 51, 21))
        self.label_2.setStyleSheet(u"image: url(:/icons/profile.png);")
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 20, 41, 21))
        self.label_3.setStyleSheet(u"image: url(:/icons/refresh.png);")
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(636, 13, 61, 21))
        self.label_6.setStyleSheet(u"image: url(:/icons/logo-no-background.png);")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(-12, 50, 581, 531))
        self.label_4.setStyleSheet(u"image: url(:/icons/dash.jpg);")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(560, 442, 141, 141))
        self.label_5.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"image: url(:/icons/inno-tech.png);\n"
"\n"
"\n"
"")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(12, 50, 531, 530))
        self.tabWidget.setLayoutDirection(Qt.LeftToRight)
        self.setting = QWidget()
        self.setting.setObjectName(u"setting")
        self.line_recdaftar = QLineEdit(self.setting)
        self.line_recdaftar.setObjectName(u"line_recdaftar")
        self.line_recdaftar.setGeometry(QRect(210, 44, 101, 41))
        self.label_7 = QLabel(self.setting)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(349, 40, 151, 41))
        self.label_8 = QLabel(self.setting)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(240, 173, 261, 41))
        self.lineEdit_2 = QLineEdit(self.setting)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(100, 233, 111, 31))
        self.lineEdit_3 = QLineEdit(self.setting)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(292, 233, 111, 31))
        self.label_9 = QLabel(self.setting)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(420, 236, 20, 21))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(True)
        self.label_9.setFont(font5)
        self.label_9.setLayoutDirection(Qt.LeftToRight)
        self.label_10 = QLabel(self.setting)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(236, 237, 21, 21))
        self.label_10.setFont(font5)
        self.label_11 = QLabel(self.setting)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(210, 293, 291, 31))
        self.btn_start = QPushButton(self.setting)
        self.btn_start.setObjectName(u"btn_start")
        self.btn_start.setGeometry(QRect(210, 363, 100, 100))
        self.btn_start.setMinimumSize(QSize(100, 100))
        self.btn_start.setMaximumSize(QSize(100, 100))
        self.btn_start.setStyleSheet(u"border-radius: 50px;\n"
"background-color: rgb(153, 255, 182);\n"
"")
        self.btn_start.setIconSize(QSize(100, 16))
        self.line_recbank = QLineEdit(self.setting)
        self.line_recbank.setObjectName(u"line_recbank")
        self.line_recbank.setGeometry(QRect(211, 113, 101, 41))
        self.label_17 = QLabel(self.setting)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(350, 109, 151, 41))
        self.tabWidget.addTab(self.setting, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tableWidget = QTableWidget(self.tab)
        if (self.tableWidget.columnCount() < 2):
            self.tableWidget.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QRect(0, 0, 540, 510))
        self.tableWidget.setMinimumSize(QSize(540, 510))
        self.tableWidget.setMaximumSize(QSize(540, 510))
        font6 = QFont()
        font6.setFamilies([u"B Nazanin"])
        font6.setPointSize(10)
        self.tableWidget.setFont(font6)
        self.tableWidget.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(37)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(210, 60, 291, 51))
        self.btn_excel = QPushButton(self.tab_2)
        self.btn_excel.setObjectName(u"btn_excel")
        self.btn_excel.setGeometry(QRect(200, 160, 141, 141))
        self.btn_excel.setMinimumSize(QSize(140, 140))
        self.btn_excel.setMaximumSize(QSize(140, 140))
        self.btn_excel.setStyleSheet(u"border-radius: 70px;\n"
"background-color: rgb(153, 255, 182);")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_4.raise_()
        self.verticalLayoutWidget.raise_()
        self.groupBox.raise_()
        self.label_5.raise_()
        self.tabWidget.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_dashboard.setText(QCoreApplication.translate("MainWindow", u"\u062f\u0627\u0634\u0628\u0648\u0631\u062f", None))
        self.btn_person.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0634\u062e\u0627\u0635", None))
        self.btn_data.setText(QCoreApplication.translate("MainWindow", u"\u062a\u062d\u0644\u06cc\u0644 \u062f\u0627\u062f\u0647", None))
        self.btn_tafazol.setText(QCoreApplication.translate("MainWindow", u"\u0645\u063a\u0627\u06cc\u0631\u062a \u06af\u06cc\u0631\u06cc", None))
        self.btn_manage.setText(QCoreApplication.translate("MainWindow", u"\u0645\u062f\u06cc\u0631\u06cc\u062a \u0628\u0648\u062f\u062c\u0647 \u0631\u06cc\u0632\u06cc", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"\u067e\u0634\u062a\u06cc\u0628\u0627\u0646\u06cc", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u0628\u0644\u0627\u06af", None))
        self.btn_call.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0645\u0627\u0633 \u0628\u0627 \u0645\u0627", None))
        self.groupBox.setTitle("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u0622\u0628\u0627\u06a9", None))
        self.lbl_calender_2.setText(QCoreApplication.translate("MainWindow", u"1402-07-18", None))
        self.lbl_0.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.label_6.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0639\u062f\u0627\u062f \u0631\u06a9\u0648\u0631\u062f \u062f\u0641\u062a\u0631 \u062e\u0648\u062f \u0631\u0627 \u0648\u0627\u0631\u062f \u06a9\u0646\u06cc\u062f:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u0628\u0627\u0632\u0647 \u0627\u06cc  \u06a9\u0647 \u0631\u06a9\u0648\u0631\u062f\u0647\u0627\u06cc \u0634\u0645\u0627 \u0631\u0627 \u0634\u0627\u0645\u0644 \u0634\u0648\u062f \u0631\u0627 \u0648\u0627\u0631\u062f \u06a9\u0646\u06cc\u062f:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0632", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0627", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u0628\u0631\u0627\u06cc \u0634\u0631\u0648\u0639 \u0641\u0631\u0622\u06cc\u0646\u062f \u0645\u063a\u0627\u06cc\u0631\u062a \u06af\u06cc\u0631\u06cc \u0628\u0631 \u0631\u0648\u06cc \u062f\u06a9\u0645\u0647 \u0632\u06cc\u0631 \u06a9\u0644\u06cc\u06a9 \u0641\u0631\u0645\u0627\u06cc\u06cc\u062f:", None))
        self.btn_start.setText(QCoreApplication.translate("MainWindow", u"\u06a9\u0644\u06cc\u06a9 \u06a9\u0646\u06cc\u062f", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0639\u062f\u0627\u062f \u0631\u06a9\u0648\u0631\u062f \u0628\u0627\u0646\u06a9 \u062e\u0648\u062f \u0631\u0627 \u0648\u0627\u0631\u062f \u06a9\u0646\u06cc\u062f:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setting), QCoreApplication.translate("MainWindow", u"\u062a\u0646\u0638\u06cc\u0645\u0627\u062a", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"\u062f\u0641\u062a\u0631", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"\u0628\u0627\u0646\u06a9", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u062e\u0631\u0648\u062c\u06cc", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u0628\u0631\u0627\u06cc \u06af\u0631\u0641\u062a\u0646 \u062e\u0631\u0648\u062c\u06cc \u0627\u06a9\u0633\u0644 \u0628\u0631\u0648 \u0631\u0648\u06cc \u0622\u06cc\u06a9\u0648\u0646 \u067e\u0627\u06cc\u06cc\u0646 \u06a9\u0644\u06cc\u06a9 \u0646\u0645\u0627\u06cc\u06cc\u062f:", None))
        self.btn_excel.setText(QCoreApplication.translate("MainWindow", u"\u06a9\u0644\u06cc\u06a9 \u0646\u0645\u0627\u06cc\u06cc\u062f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u062e\u0631\u0648\u062c\u06cc \u0627\u06a9\u0633\u0644", None))
    # retranslateUi

